CREATE TABLE noteful_folders (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  folder_name TEXT NOT NULL,
);

-- Do I need to include a column with the date (either published or modified?)
-- Do I need to CASCADE here to handle deleting a folder?