CREATE TABLE notes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  content TEXT,
  folder_id INTEGER REFERENCES folders(id) ON DELETE CASCADE NOT NULL,
  modified TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO notes (
  name, content, folder_id
)
values ('My favorite cat', 'This cat is the best', 1);